#
#spring:
#  datasource:
#    url: jdbc:mysql://rm-cn-zpr3gvmud001ea1o.rwlb.cn-chengdu.rds.aliyuncs.com:3306/mybatis_9_19?characterEncoding=utf-8&serverTimezone=UTC
#    username: root
#    password: 123456ABCabc
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  application:
#    name: user-service
#    cloud:
#      nacos:
#        discovery:
#          server-addr: 127.0.0.1:8848
#mybatis-plus:
#  mapper-locations: classpath*:/mapper/**/*.xml
#  #  逻辑删除插件
#  global-config:
#    db-config:
#      logic-delete-field: del_flag # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
#      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
#      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
#server:
#  port: 8085
##    url: jdbc:mysql://localhost:3306/你的数据库名?characterEncoding=utf-8&serverTimezone=UTC
#
## 配置日志的保存名称
#logging:
#  file:
#    name: mylog.log


spring:
  datasource:
#    url: jdbc:mysql://rm-cn-zpr3gvmud001ea1o.rwlb.cn-chengdu.rds.aliyuncs.com:3306/mybatis_9_19?characterEncoding=utf-8&serverTimezone=UTC
    #    url: jdbc:mysql://localhost:3306/docker_dataBase?characterEncoding=utf-8&serverTimezone=UTC  #新的未分块数据库
    url: jdbc:mysql://localhost:3306/fault?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: fault-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      logic-delete-field: del_flag # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
server:
  port: 8082

# 配置日志的保存名称
logging:
  file:
    name: mylog.log
