server:
  port: 9000
spring:
  application:
    name: gateway-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
#          filters:  # 路由过滤器过滤第一个路径段 比如在postman中 访问http://localhost:9000/user/login 则访问http://localhost:8081/login
#            - StripPrefix=1

        - id: role-service
          uri: lb://role-service
          predicates:
            - Path=/role/**
#          filters:
#            - StripPrefix=1

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order/**
#          filters:
#            - StripPrefix=1

        - id: item-service
          uri: lb://item-service
          predicates:
            - Path=/item/**
#          filters:
#            - StripPrefix=1

        - id: fault-service
          uri: lb://fault-service
          predicates:
            - Path=/fault/**
#          filters:
#            - StripPrefix=1


        - id: device-service
          uri: lb://device-service
          predicates:
            - Path=/device/**
#          filters:
#            - StripPrefix=1
